//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PV178.Homeworks.Homework3.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PV178.Homeworks.Homework3.Tests.TestData", typeof(TestData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [&quot;AR230&quot;,&quot;BA326&quot;,&quot;BI404&quot;,&quot;CH385&quot;,&quot;PH206&quot;,&quot;PH216&quot;,&quot;G-CI333&quot;,&quot;CI401&quot;,&quot;EE210&quot;,&quot;EN111C&quot;,&quot;HI361&quot;,&quot;PA150&quot;,&quot;PA232&quot;,&quot;PR104&quot;,&quot;PR414&quot;,&quot;PY375&quot;,&quot;SO375&quot;,&quot;SO475&quot;,&quot;TE385&quot;].
        /// </summary>
        internal static string Results_CoursesWithoutBook {
            get {
                return ResourceManager.GetString("Results_CoursesWithoutBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;Item1&quot;:&quot;AR202&quot;,&quot;Item2&quot;:&quot;Art&quot;},{&quot;Item1&quot;:&quot;AR203&quot;,&quot;Item2&quot;:&quot;Art&quot;},{&quot;Item1&quot;:&quot;AR210&quot;,&quot;Item2&quot;:&quot;Art&quot;},{&quot;Item1&quot;:&quot;AR230&quot;,&quot;Item2&quot;:&quot;Art&quot;},{&quot;Item1&quot;:&quot;G-AR350&quot;,&quot;Item2&quot;:&quot;ART&quot;},{&quot;Item1&quot;:&quot;AR475A&quot;,&quot;Item2&quot;:&quot;Art&quot;},{&quot;Item1&quot;:&quot;G-AR131&quot;,&quot;Item2&quot;:&quot;Art&quot;},{&quot;Item1&quot;:&quot;G-AR311&quot;,&quot;Item2&quot;:&quot;ART&quot;},{&quot;Item1&quot;:&quot;AC206&quot;,&quot;Item2&quot;:&quot;Business Administration&quot;},{&quot;Item1&quot;:&quot;AC306&quot;,&quot;Item2&quot;:&quot;Business Administration&quot;},{&quot;Item1&quot;:&quot;AC320&quot;,&quot;Item2&quot;:&quot;Business Administration&quot;},{&quot;Item1&quot;:&quot;BA224&quot;,&quot;Item2&quot;:&quot;Business Administration&quot;},{&quot;Item1&quot;:&quot;BI315&quot;,&quot;Item2&quot;:&quot;Business....
        /// </summary>
        internal static string Results_ListAllCoursesWithArea {
            get {
                return ResourceManager.GetString("Results_ListAllCoursesWithArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [&quot;Art&quot;,&quot;Business Administration&quot;,&quot;Natural Sciences&quot;,&quot;Curriculum &amp; Instruction&quot;,&quot;Communication&quot;,&quot;English&quot;,&quot;History&quot;,&quot;Interdisciplinary&quot;,&quot;Mathematics&quot;,&quot;Modern Languages&quot;,&quot;Designing and Drawing for the Theatre&quot;,&quot;Physical Education&quot;,&quot;Philosophy and Religion&quot;,&quot;Political Science&quot;,&quot;Exploring Psychology in Modules&quot;,&quot;Special Education&quot;,&quot;Sociology&quot;,&quot;Technology&quot;].
        /// </summary>
        internal static string Results_ListAreas {
            get {
                return ResourceManager.GetString("Results_ListAreas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;Item1&quot;:&quot;BA326&quot;,&quot;Item2&quot;:0},{&quot;Item1&quot;:&quot;EN111A&quot;,&quot;Item2&quot;:2},{&quot;Item1&quot;:&quot;ML209&quot;,&quot;Item2&quot;:2}].
        /// </summary>
        internal static string Results_ListBookCountPerCourseUsingJoin {
            get {
                return ResourceManager.GetString("Results_ListBookCountPerCourseUsingJoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [&quot;AC320&quot;,&quot;BA320&quot;].
        /// </summary>
        internal static string Results_ListCoursesWithMostExpensiveBook {
            get {
                return ResourceManager.GetString("Results_ListCoursesWithMostExpensiveBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;Item1&quot;:&quot;Conyers&quot;,&quot;Item2&quot;:4},{&quot;Item1&quot;:&quot;Zerger&quot;,&quot;Item2&quot;:4},{&quot;Item1&quot;:&quot;Erwy-Shr&quot;,&quot;Item2&quot;:1},{&quot;Item1&quot;:&quot;O&apos;Dell&quot;,&quot;Item2&quot;:2},{&quot;Item1&quot;:&quot;Martin&quot;,&quot;Item2&quot;:4},{&quot;Item1&quot;:&quot;Whalen&quot;,&quot;Item2&quot;:4},{&quot;Item1&quot;:&quot;Gselman&quot;,&quot;Item2&quot;:4},{&quot;Item1&quot;:&quot;Weller&quot;,&quot;Item2&quot;:1},{&quot;Item1&quot;:&quot;Ayella&quot;,&quot;Item2&quot;:3},{&quot;Item1&quot;:&quot;Frye&quot;,&quot;Item2&quot;:4},{&quot;Item1&quot;:&quot;Wilgers&quot;,&quot;Item2&quot;:2},{&quot;Item1&quot;:&quot;vanAsselt&quot;,&quot;Item2&quot;:3},{&quot;Item1&quot;:&quot;Koralegdra&quot;,&quot;Item2&quot;:2},{&quot;Item1&quot;:&quot;Kirchner&quot;,&quot;Item2&quot;:2},{&quot;Item1&quot;:&quot;ACCK&quot;,&quot;Item2&quot;:6},{&quot;Item1&quot;:&quot;Maclin&quot;,&quot;Item2&quot;:4},{&quot;Item1&quot;:&quot;Kimbrell&quot;,&quot;Item2&quot;:3},....
        /// </summary>
        internal static string Results_ListTeachers {
            get {
                return ResourceManager.GetString("Results_ListTeachers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;Item1&quot;:&quot;Conyers&quot;,&quot;Item2&quot;:[&quot;Methods of Tchng Art&quot;]},{&quot;Item1&quot;:&quot;Zerger&quot;,&quot;Item2&quot;:[]},{&quot;Item1&quot;:&quot;Erwy-Shr&quot;,&quot;Item2&quot;:[&quot;Graphic Design I&quot;]},{&quot;Item1&quot;:&quot;O&apos;Dell&quot;,&quot;Item2&quot;:[]},{&quot;Item1&quot;:&quot;Martin&quot;,&quot;Item2&quot;:[]},{&quot;Item1&quot;:&quot;Whalen&quot;,&quot;Item2&quot;:[]},{&quot;Item1&quot;:&quot;Gselman&quot;,&quot;Item2&quot;:[&quot;Financial Management II&quot;]},{&quot;Item1&quot;:&quot;Weller&quot;,&quot;Item2&quot;:[]},{&quot;Item1&quot;:&quot;Ayella&quot;,&quot;Item2&quot;:[]},{&quot;Item1&quot;:&quot;Frye&quot;,&quot;Item2&quot;:[&quot;Biomedical Ethics&quot;,&quot;Biomedical Ethics&quot;]},{&quot;Item1&quot;:&quot;Wilgers&quot;,&quot;Item2&quot;:[]},{&quot;Item1&quot;:&quot;vanAsselt&quot;,&quot;Item2&quot;:[&quot;Adv Inorganic Chemistry&quot;,&quot;College Physics I [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Results_ListTeachersAndCoursesWithoutBook {
            get {
                return ResourceManager.GetString("Results_ListTeachersAndCoursesWithoutBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [&quot;Methods for Effective Teaching&quot;,&quot;Teachers, Schools &amp; Society&quot;,&quot;Bridging English&quot;].
        /// </summary>
        internal static string Results_ListThreeMostExpensiveBooks {
            get {
                return ResourceManager.GetString("Results_ListThreeMostExpensiveBooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;CourseCode&quot;:&quot;AR202&quot;,&quot;Teacher&quot;:&quot;Conyers&quot;,&quot;Area&quot;:&quot;Art&quot;,&quot;Course&quot;:&quot;Painting II: Watercolor&quot;,&quot;Book&quot;:&quot;Everything You Ever Wanted to Know&quot;,&quot;Edition&quot;:null,&quot;Author&quot;:null,&quot;Ibsn&quot;:&quot;0-82305649x&quot;,&quot;New&quot;:26,&quot;Used&quot;:null,&quot;Rent&quot;:null},{&quot;CourseCode&quot;:&quot;AR203&quot;,&quot;Teacher&quot;:&quot;Zerger&quot;,&quot;Area&quot;:&quot;Art&quot;,&quot;Course&quot;:&quot;Photography&quot;,&quot;Book&quot;:&quot;Photography&quot;,&quot;Edition&quot;:10,&quot;Author&quot;:&quot;Upton&quot;,&quot;Ibsn&quot;:&quot;0-205711499&quot;,&quot;New&quot;:133,&quot;Used&quot;:null,&quot;Rent&quot;:58},{&quot;CourseCode&quot;:&quot;AR210&quot;,&quot;Teacher&quot;:&quot;Zerger&quot;,&quot;Area&quot;:&quot;Art&quot;,&quot;Course&quot;:&quot;Drawing II&quot;,&quot;Book&quot;:&quot;Drawing Manual Vilppu&quot;,&quot;Edi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestData1 {
            get {
                return ResourceManager.GetString("TestData1", resourceCulture);
            }
        }
    }
}
