//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PV178.Homeworks.Homework2.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SampleData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SampleData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PV178.Homeworks.Homework2.Tests.SampleData", typeof(SampleData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2014-03-20 13:45:01;&quot;mssql1.fi.muni.cz&quot;;9002;17;&quot;tempdb&quot;;&quot;The log file for database &apos;tempdb&apos; is full. Back up the transaction log for the database to free up some log space&quot;
        ///2014-03-20 17:06:37;&quot;mssql1.fi.muni.cz&quot;;9002;17;&quot;pv178&quot;;&quot;The log file for database &apos;pv178&apos; is full. Back up the transaction log for the database to free up some log space&quot;
        ///2014-03-21 07:22:05;&quot;mssql2.fi.muni.cz&quot;;9002;17;&quot;is&quot;;&quot;The log file for database &apos;is&apos; is full. Back up the transaction log for the database to free up some log space [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CsvFormatLog {
            get {
                return ResourceManager.GetString("CsvFormatLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9002;2014-03-20 13:45:01;&quot;mssql1.fi.muni.cz&quot;;17;&quot;tempdb&quot;;&quot;The log file for database &apos;tempdb&apos; is full. Back up the transaction log for the database to free up some log space&quot;
        ///9002;2014-03-20 17:06:37;&quot;mssql1.fi.muni.cz&quot;;17;&quot;pv178&quot;;&quot;The log file for database &apos;pv178&apos; is full. Back up the transaction log for the database to free up some log space&quot;
        ///9002;2014-03-21 07:22:05;&quot;mssql2.fi.muni.cz&quot;;17;&quot;is&quot;;&quot;The log file for database &apos;is&apos; is full. Back up the transaction log for the database to free up some log space [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CsvFormatLog2 {
            get {
                return ResourceManager.GetString("CsvFormatLog2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EventTime;ServerName;ErrorNumber;ErrorSeverity;DatabaseName;ErrorMessage
        ///2014-03-20 13:45:01;&quot;mssql1.fi.muni.cz&quot;;9002;17;&quot;tempdb&quot;;&quot;The log file for database &apos;tempdb&apos; is full. Back up the transaction log for the database to free up some log space&quot;
        ///2014-03-20 17:06:37;&quot;mssql1.fi.muni.cz&quot;;9002;17;&quot;pv178&quot;;&quot;The log file for database &apos;pv178&apos; is full. Back up the transaction log for the database to free up some log space&quot;
        ///2014-03-21 07:22:05;&quot;mssql2.fi.muni.cz&quot;;9002;17;&quot;is&quot;;&quot;The log file for database &apos;is&apos; is fu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CsvFormatLogWithHeader {
            get {
                return ResourceManager.GetString("CsvFormatLogWithHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;EventTime&quot;:&quot;2014-03-20T13:45:01&quot;,&quot;ServerName&quot;:&quot;mssql1.fi.muni.cz&quot;,&quot;ErrorNumber&quot;:9002,&quot;ErrorSeverity&quot;:17,&quot;DatabaseName&quot;:&quot;tempdb&quot;,&quot;ErrorMessage&quot;:&quot;The log file for database &apos;tempdb&apos; is full. Back up the transaction log for the database to free up some log space&quot;},{&quot;EventTime&quot;:&quot;2014-03-20T17:06:37&quot;,&quot;ServerName&quot;:&quot;mssql1.fi.muni.cz&quot;,&quot;ErrorNumber&quot;:9002,&quot;ErrorSeverity&quot;:17,&quot;DatabaseName&quot;:&quot;pv178&quot;,&quot;ErrorMessage&quot;:&quot;The log file for database &apos;pv178&apos; is full. Back up the transaction log for the database to free up some [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JsonFormatLog {
            get {
                return ResourceManager.GetString("JsonFormatLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2014-03-20 13:45:01: Error 9002 (severity 17) at SQL Server &apos;mssql1.fi.muni.cz&apos;: The log file for database &apos;tempdb&apos; is full. Back up the transaction log for the database to free up some log space
        ///2014-03-20 17:06:37: Error 9002 (severity 17) at SQL Server &apos;mssql1.fi.muni.cz&apos;: The log file for database &apos;pv178&apos; is full. Back up the transaction log for the database to free up some log space
        ///2014-03-21 07:22:05: Error 9002 (severity 17) at SQL Server &apos;mssql2.fi.muni.cz&apos;: The log file for database &apos;is&apos; is full [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SQLServerFormatLog {
            get {
                return ResourceManager.GetString("SQLServerFormatLog", resourceCulture);
            }
        }
    }
}
